### ISSUE TITLE
ServiceArea

### ISSUE THREAD

**Issue by rpont** [alexronquillo/optimal-airport#1]
Need to discuss what happens if wrong type plane it sent to wrong type of ServiceArea. See TestServiceArea.java

**Comment by alexronquillo** [comment]
An incorrect plane type should never enter a service area, so I think we should either take the airplane out of the system and continue the simulation (which I don't think I really like because it isn't realistic - those passengers/cargo still have be unloaded sometime) or just exit the simulation with an error. We can put some debug assertions in the code because this case should never happen.

**Comment by rpont** [comment]
I think that we should just exit the system with the error message. As you said, we are coding this to never happen. Although we can't say it never happen, it shouldn't, and if it does that means the simulation is not executing correctly and therefore should be terminated and fixed.
